export const ADD_To_CART = 'ADD_To_CART'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'
export const UPDATE_FROM_CART = 'UPDATE_FROM_CART'
export const PRODUCT_TO_CART = 'PRODUCT_TO_CART'   
export const SUB_TOTAL = 'SUB_TOTAL'

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST'
export const DELETE_FROM_WISHLIST = 'DELETE_FROM_WISHLIST'